In [1]:
from sklearn.datasets import load_boston
boston = load_boston()

In [2]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [3]:
print(boston["DESCR"])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [4]:
boston["data"]

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
boston["data"].shape

(506, 13)

In [6]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(boston["data"],boston["target"],test_size = 0.30,random_state = 42)

In [7]:
lr = LinearRegression()

In [8]:
model = lr.fit(X_train,y_train)

In [9]:
lr.score(X_test,y_test)

0.7112260057484878

In [10]:
lr.intercept_

31.631084035691455

In [11]:
lr.coef_

array([-1.33470103e-01,  3.58089136e-02,  4.95226452e-02,  3.11983512e+00,
       -1.54170609e+01,  4.05719923e+00, -1.08208352e-02, -1.38599824e+00,
        2.42727340e-01, -8.70223437e-03, -9.10685208e-01,  1.17941159e-02,
       -5.47113313e-01])

In [12]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(boston["data"],boston["target"],test_size = 0.33,random_state = 42)

In [13]:
lr = LinearRegression()

In [14]:
model = lr.fit(X_train,y_train)

In [15]:
lr.score(X_test,y_test)

0.7261570836552487

In [16]:
lr.intercept_

33.33497575563612

In [17]:
lr.coef_

array([-1.28749718e-01,  3.78232228e-02,  5.82109233e-02,  3.23866812e+00,
       -1.61698120e+01,  3.90205116e+00, -1.28507825e-02, -1.42222430e+00,
        2.34853915e-01, -8.21331947e-03, -9.28722459e-01,  1.17695921e-02,
       -5.47566338e-01])

In [18]:
x_test = y_test(actual)

NameError: name 'actual' is not defined

In [19]:
x_test = y_test (actual)

NameError: name 'actual' is not defined

In [20]:
x_test = y_test (actual)

NameError: name 'actual' is not defined

In [21]:
X_test = y_test (actual)

NameError: name 'actual' is not defined

In [22]:
lr.coef_

array([-1.28749718e-01,  3.78232228e-02,  5.82109233e-02,  3.23866812e+00,
       -1.61698120e+01,  3.90205116e+00, -1.28507825e-02, -1.42222430e+00,
        2.34853915e-01, -8.21331947e-03, -9.28722459e-01,  1.17695921e-02,
       -5.47566338e-01])

In [23]:
x_test = y_test (actual)


NameError: name 'actual' is not defined

In [24]:
x_test = y_test

In [25]:
predictions = lr.predict(X_test)

In [26]:
predictions

array([28.53469469, 36.6187006 , 15.63751079, 25.5014496 , 18.7096734 ,
       23.16471591, 17.31011035, 14.07736367, 23.01064388, 20.54223482,
       24.91632351, 18.41098052, -6.52079687, 21.83372604, 19.14903064,
       26.0587322 , 20.30232625,  5.74943567, 40.33137811, 17.45791446,
       27.47486665, 30.2170757 , 10.80555625, 23.87721728, 17.99492211,
       16.02608791, 23.268288  , 14.36825207, 22.38116971, 19.3092068 ,
       22.17284576, 25.05925441, 25.13780726, 18.46730198, 16.60405712,
       17.46564046, 30.71367733, 20.05106788, 23.9897768 , 24.94322408,
       13.97945355, 31.64706967, 42.48057206, 17.70042814, 26.92507869,
       17.15897719, 13.68918087, 26.14924245, 20.2782306 , 29.99003492,
       21.21260347, 34.03649185, 15.41837553, 25.95781061, 39.13897274,
       22.96118424, 18.80310558, 33.07865362, 24.74384155, 12.83640958,
       22.41963398, 30.64804979, 31.59567111, 16.34088197, 20.9504304 ,
       16.70145875, 20.23215646, 26.1437865 , 31.12160889, 11.89

In [27]:
y_test

array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4, 12. , 19.9, 19.4, 13.4, 18.2, 24.6, 21.1, 24.7,
        8.7, 27.5, 20.7, 36.2, 31.6, 11.7, 39.8, 13.9, 21.8, 23.7, 17.6,
       24.4,  8.8, 19.2, 25.3, 20.4, 23.1, 37.9, 15.6, 45.4, 15.7, 22.6,
       14.5, 18.7, 17.8, 16.1, 20.6, 31.6, 29.1, 15.6, 17.5, 22.5, 19.4,
       19.3,  8.5, 20.6, 17. , 17.1, 14.5, 50. , 14

In [28]:
from sklearn import metrics
import numpy as np

In [29]:
print("MAE",metrics.mean_absolute-error(y_test,predictions))

AttributeError: module 'sklearn.metrics' has no attribute 'mean_absolute'

In [30]:
print ("MAE",metrics.mean_absolute_error(y_test,predictions))

MAE 3.1482557548168115


In [31]:
print("MSE",metrics.mean_squared_error(y_test,predictions))

MSE 20.72402343733967


In [32]:
print("MSE",metrics.mean_squared_error(x_test,predictions))

MSE 20.72402343733967


In [33]:
print("MAE",metrics.mean_absolute_error(x_test,predictions))

MAE 3.1482557548168115


In [34]:
# check version of libraries
import sys
import scipy
import matplotlib
import pandas
import sklearn

print('Python :',sys.version)
print('Scipy :',scipy.__version__)
print('matplotlib : ',matplotlib.__version__)
print('pandas :',pandas.__version__)
print('sklearn :',sklearn.__version__)


Python : 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Scipy : 1.4.1
matplotlib :  3.1.3
pandas : 1.0.1
sklearn : 0.22.1


In [35]:
import statsmodels.formula.api as sm

In [36]:
t = df["X_test"]
c = df["y_test"]

NameError: name 'df' is not defined

In [37]:
lr.coef_

array([-1.28749718e-01,  3.78232228e-02,  5.82109233e-02,  3.23866812e+00,
       -1.61698120e+01,  3.90205116e+00, -1.28507825e-02, -1.42222430e+00,
        2.34853915e-01, -8.21331947e-03, -9.28722459e-01,  1.17695921e-02,
       -5.47566338e-01])

In [38]:
import pandas as pd

In [39]:
no_of_ads = [1,3,2,1,3,7,5,4,6,8]
no_of_houses_sold = [14,24,18,17,27,45,10,18,89,17]

In [40]:
print(list(zip(no_of_ads,no_of_houses_sold)))

[(1, 14), (3, 24), (2, 18), (1, 17), (3, 27), (7, 45), (5, 10), (4, 18), (6, 89), (8, 17)]


In [41]:
df = pd.DataFrame(list(zip(no_of_ads,no_of_houses_sold)),columns=["no of ads","no of houses sold"])

In [42]:
df

no of ads  no of houses sold
0          1                 14
1          3                 24
2          2                 18
3          1                 17
4          3                 27
5          7                 45
6          5                 10
7          4                 18
8          6                 89
9          8                 17

In [43]:
X = df[["no of ads"]]

In [45]:
y = df[["no of houses sold"]]

In [46]:
X

no of ads
0          1
1          3
2          2
3          1
4          3
5          7
6          5
7          4
8          6
9          8

In [47]:
y

no of houses sold
0                 14
1                 24
2                 18
3                 17
4                 27
5                 45
6                 10
7                 18
8                 89
9                 17

In [48]:
import statsmodels.formula.api as sm

In [49]:
a = df["no of ads"]
b = df["no of houses sold"]

In [50]:
import statsmodel.api as s

ModuleNotFoundError: No module named 'statsmodel'

In [51]:
import statsmodels.api as s

In [52]:
t = s.add_constant(t)

NameError: name 't' is not defined

In [53]:
import statsmodels.api as s

In [54]:
a = s.add_constant(a)

In [55]:
model = sm.OLS(b,a)

AttributeError: module 'statsmodels.formula.api' has no attribute 'OLS'

In [56]:
model = sm.CRIM(b,a)

AttributeError: module 'statsmodels.formula.api' has no attribute 'CRIM'

In [57]:
import statsmodels.formula.api as sm


In [58]:
t = df["no of ads"]
c = df["no of houses sold"]

In [59]:
import statsmodels.api as s

In [60]:
t = s.add_constant(t)

In [61]:
model = sm.OLS(c,t)

AttributeError: module 'statsmodels.formula.api' has no attribute 'OLS'

In [62]:
model = sm.TLS(c,t)

AttributeError: module 'statsmodels.formula.api' has no attribute 'TLS'

In [63]:
model = sm.OLS(c,t)

AttributeError: module 'statsmodels.formula.api' has no attribute 'OLS'

In [64]:
model = s.OLS(c,t)

In [65]:
model

In [66]:
result = model.fit()

In [67]:
print.(result(summary))

SyntaxError: invalid syntax (<ipython-input-67-b23fb5cc0636>, line 1)

In [68]:
print(result.(summary))

SyntaxError: invalid syntax (<ipython-input-68-ad0657405982>, line 1)

In [69]:
print(result.summary)

<bound method RegressionResults.summary of <statsmodels.regression.linear_model.OLSResults object at 0x000002563C5C9548>>


In [70]:
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:      no of houses sold   R-squared:                       0.165
Model:                            OLS   Adj. R-squared:                  0.061
Method:                 Least Squares   F-statistic:                     1.584
Date:                Thu, 14 May 2020   Prob (F-statistic):              0.244
Time:                        20:51:52   Log-Likelihood:                -44.348
No. Observations:                  10   AIC:                             92.70
Df Residuals:                       8   BIC:                             93.30
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         12.2704     14.363      0.854      0.4

C:\ProgramData\Anaconda3\lib\site-packages\scipy\stats\stats.py:1535: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=10
  "anyway, n=%i" % int(n))


In [71]:
model = s.OLS(c,t)

In [72]:
model

In [73]:
result = model.fit()

In [74]:
print(result.summary())

                            OLS Regression Results                            
Dep. Variable:      no of houses sold   R-squared:                       0.165
Model:                            OLS   Adj. R-squared:                  0.061
Method:                 Least Squares   F-statistic:                     1.584
Date:                Thu, 14 May 2020   Prob (F-statistic):              0.244
Time:                        20:55:30   Log-Likelihood:                -44.348
No. Observations:                  10   AIC:                             92.70
Df Residuals:                       8   BIC:                             93.30
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         12.2704     14.363      0.854      0.4